CREATE DATABASE toko;

USE toko;

CREATE TABLE barang(
    KODE VARCHAR(255) PRIMARY KEY,
    NAMA VARCHAR(255),
    HARGA DOUBLE
);

CREATE TABLE pelanggan(
    KODE VARCHAR(255) PRIMARY KEY,
    NAMA VARCHAR(255),
    ALAMAT VARCHAR(255)
);

CREATE TABLE transaksi(
    KODE VARCHAR(255) PRIMARY KEY,
    TANGGAL DATE,
    KODE_PELANGGAN VARCHAR(255),
    KODE_BARANG VARCHAR(255),
    JUMLAH_BARANG DOUBLE
);